services:
  ############################# Backend NESTJS
  backend:
    build:
      context: ./apps/nest
      dockerfile: Dockerfile.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8000"
    volumes:
      - ./apps/nest:/app
      # - ia_nest_node_modules:/app/node_modules
      - ./app/nest/src/infras/clients/kafka/certs:/app/src/infras/clients/kafka/certs
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      NODE_ENV: development
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_CA_CERT_PATH: ${KAFKA_CA_CERT_PATH}
      KAFKA_CLIENT_CERT_PATH: ${KAFKA_CLIENT_CERT_PATH}
      KAFKA_CLIENT_KEY_PATH: ${KAFKA_CLIENT_KEY_PATH}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    depends_on:
      db:
        condition: service_started
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ia_onelineBook_network
  ############################# Frontend NEXT.JS
  nextjs:
    build:
      context: ./apps/client-next
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # 🔥 On mappe le port 3000 du conteneur vers 3001 sur l'hôte
    volumes:
      - ./apps/client-next:/app
      - ia_next_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    command: npm run dev
    networks:
      - ia_onelineBook_network

  ############################# Database MYSQL
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ia_db_data:/var/lib/mysql
    networks:
      - ia_onelineBook_network
  ############################# Zookeeper
  zookeeper:
    # latest en local c'est c'est ok mais  en prod il faut un tag precis
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ia_onelineBook_network
  ############################# Message Broker KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
    - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - ia_onelineBook_network
    healthcheck:
      test:
        [
          "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
  ############################# Message Broker KAFKA
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - ia_onelineBook_network
  ############################# Redis
  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass mystrongpassword
    environment:
      - REDIS_PASSWORD=mystrongpassword
    networks:
      - ia_onelineBook_network

volumes:
  ia_db_data:
  ia_react_node_modules:
  ia_nest_node_modules:
  ia_next_node_modules:
  ia_zookeeper_data:
    driver: local
  ia_kafka_data:
    driver: local

networks:
  ia_onelineBook_network: # 🔥 Définition du réseau
    driver: bridge