# Étape 1 : Utiliser une image Node.js légère
FROM node:20 as development

# Étape de nettoyage avant la construction
RUN rm -rf /app/dist/*

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour optimiser le cache Docker
COPY package*.json ./

# Copier les certificats Kafka dans le conteneur
COPY ./src/infras/clients/kafka/certs /app/dist/infras/clients/kafka/certs

# Copier tout le code source
COPY . .


COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
# Installer les dépendances nécessaires pour le développement
RUN npm install


ENV NODE_ENV=development


# Exposer le port utilisé par votre application NestJS (par défaut 3000)
EXPOSE 8000

# Commande pour démarrer l'application en mode développement
# npm run dev
CMD ["npm", "run", "start:dev"]
